name: Feature Request
description: 新しい機能の要望や、既存の機能の改善についての提案
title: "[要望] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        複数の要望・提案がある場合は、ひとつずつ別々のissueとして登録してください。
  - type: textarea
    id: proposal
    attributes:
      label: 要望・提案の内容
      description: 新しい機能の要望や、既存の機能の改善についての提案をできるだけ詳しくお書きください。
      placeholder: 内容をできるだけ詳しく記載してください。
      value: できるだけ詳しく記載してください。
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        対応や回答をお約束するものではありませんのでご注意ください。
